#+OPTIONS: toc:nil  
#+OPTIONS: num:nil
#+TITLE: Debian cross-gcc snapshot packages

* Overview

This is an APT repository that provides unofficial snapshot Debian packages for
GCC cross-compilers. These compilers use [[https://wiki.debian.org/Multiarch][multi-arch]] libraries. These are built
from the sources for GCC 4.9, as described on the [[https://wiki.debian.org/MultiarchCrossToolchainBuild#Local_building_of_multiarch_cross-toolchains][Debian wiki]]. The bulk of the
logic to do cross-building is already present in the Debian sources. These
packages use /very/ light patches to the debianization.

These packages are a stop-gap measure, until packages such as these can be
pushed into the main Debian repo. When that happens, I will stop building these.

These are rebuilt every week, so things should be reasonably up-to-date. I
attempt to build compilers targeting

- armel
- armhf
- mips
- mipsel
- powerpc

Some subset of these usually fails, and will not be built for that week. As of
this writing (2014-07-20), mipsel and powerpc are failing. The compiler for the
following languages are built:

- C
- C++
- Fortran
- Java
- Go
- Objective C
- Objective C++

*Packages are generated weekly by a script and not tested by anybody. Use at
your own risk.*

These packages are built for the =amd64= architecture. Debian/wheezy is
targeted, and things should work there and on Debian/sid.

* Instructions

Add to your =/etc/apt/sources.list=:

#+BEGIN_EXAMPLE
deb     http://toolchains.secretsauce.net unstable main
deb-src http://toolchains.secretsauce.net unstable main
#+END_EXAMPLE

To tell APT to trust these packages, do

#+BEGIN_EXAMPLE
wget -q -O - http://toolchains.secretsauce.net/key.gpg | sudo apt-key add -
#+END_EXAMPLE

* Sources

This repository is populated by a script and a few patches; those appear here:

https://github.com/dkogan/toolchains

* Contact

The maintainer is Dima Kogan <dima at secretsauce dot net>. He knows about these
packages specifically; for more general cross-building-on-Debian inquiries, read
the Debian wiki, or ask on IRC: #emdebian on irc.oftc.net.
